[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

; Tu dong clon thu vien ve
lib_deps =
    miguelbalboa/MFRC522 @ ^1.4.11
    chris--a/Keypad @ ^3.1.1
    adafruit/Adafruit SH110X @ ^2.1.10
    adafruit/Adafruit GFX Library @ ^1.11.9
    blynkkk/Blynk @ ^1.3.2
